### ISSUE TITLE
Missing Kustomize v3 compatibility

### ISSUE THREAD

**Issue by MarioUhrik** [sighup-io/fury-kubernetes-jenkins#5]
At the moment, the Jenkins manifests are not kustomize v3 compatible because of the `secretGenerator` syntax within.
This makes `fury-kubernetes-jenkins` one of the last Fury modules that aren't kustomize v3 compatible.

For the sake of making it kustomize v3 compatible, it's sufficient to change all `secretGenerator` sections as follows.

```YAML
secretGenerator:
  - name: jenkins-agent
    commands:
      jenkins-agent-name: "/bin/echo -n jenkins-k8s-minion"
      jenkins-agent-secret: "/bin/echo -n 123456"
```
->
```YAML
secretGenerator:
  - name: jenkins-agent
    literals:
     - jenkins-agent-name=jenkins-k8s-minion
     - jenkins-agent-secret=123456
```
