### ISSUE TITLE
Consider using SIGHUP's own jenkins-agent image

### ISSUE THREAD

**Issue by MarioUhrik** [sighup-io/fury-kubernetes-jenkins#6]
SIGHUP currently maintains a jenkins-agent image at `quay.io`, but it's not actually used by default in `fury-kubernetes-jenkins`. This is not ideal, because the `quay.io/sighup/jenkins-agent-kubectl` contains kubectl, kustomize, git-crypt, and other goodies. In order to take advantage of this, it's necessary to patch the deployment e.g. like this:
```YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-agent
spec:
  template:
    spec:
      containers:
        - name: jenkins
          image: quay.io/sighup/jenkins-agent-kubectl:1.12.6_1.0.10
```

Please consider making https://github.com/sighupio/fury-images/tree/master/jenkins-agent-kubectl the default image of the `jenkins/jenkins-agent` Fury package, or making this clear in this project's documentation.
